/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var l=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var u=Object.prototype.hasOwnProperty;var g=(c,o)=>{for(var e in o)l(c,e,{get:o[e],enumerable:!0})},x=(c,o,e,t)=>{if(o&&typeof o=="object"||typeof o=="function")for(let n of p(o))!u.call(c,n)&&n!==e&&l(c,n,{get:()=>o[n],enumerable:!(t=h(o,n))||t.enumerable});return c};var M=c=>x(l({},"__esModule",{value:!0}),c);var b={};g(b,{default:()=>r});module.exports=M(b);var m=require("obsidian"),r=class extends m.Plugin{constructor(){super(...arguments);this.recipeTimes={"Iron Gear":.5,"Copper Cable":.2}}async onload(){console.log("Obsitest plugin loaded"),this.registerMarkdownCodeBlockProcessor("factory",(e,t,n)=>{let i=this.parseFactoryBlock(e),s=this.calculateProductionRate(i.recipe,i.machines),a=this.createMachineBox(i.recipe,i.machines,s);t.appendChild(a)})}parseFactoryBlock(e){let t=e.split(`
`),n=t.find(d=>d.startsWith("recipe")),i=t.find(d=>d.startsWith("machines")),s=n?n.split(":")[1].trim():"",a=i?parseInt(i.split(":")[1].trim()):0;return{recipe:s,machines:a}}calculateProductionRate(e,t){let n=this.recipeTimes[e]||1;return(t/n*60).toFixed(2)}createMachineBox(e,t,n){let i=document.createElement("div");i.classList.add("machine-box");let s="factoricons/assembling-machine-2.png";return i.innerHTML=`
        <img src="${s}" style="width: 64px; height: 64px;">
        <strong>Recipe:</strong> ${e}<br>
        <strong>Machines:</strong> ${t}<br>
        <strong>Production Rate:</strong> ${n} items/minute
    `,i}addRow(){let e=document.createElement("div");e.classList.add("machine-row");let t=document.createElement("button");t.innerText="Add Machine",t.onclick=()=>this.addMachineBox(e),e.appendChild(t),document.body.appendChild(e)}addMachineBox(e){let t=this.createMachineBox("Iron Gear",5,"10/s");e.appendChild(t)}onunload(){console.log("Obsitest plugin unloaded")}};
